### PR TITLE
Fix: errors in sz.rs, also much cleaner

### LINKED ISSUE #22: Bug in sz.rs
I found some bugs in sz.rs

1. the filtering does not work at all
2. The number of tokens is way off, its actually counting the number of lines.

### PR DESCRIPTION
**Pull request by 21st-centuryman**
closes #22 

I manage to make it much cleaner as well, lines was not needed. However we did add some lines but it will overlal be less when we compress the files.

### CODE REVIEW

**Comment by 21st-centuryman** [comment]
Check the test code, it returns NaN on files we haven't added and the proper tokens/lines on realize.rs

Please note we will have more tokens/line than teenygrad since rust has curly braces and a lot more stuff that needs to be added for it to run.

**Comment by 21st-centuryman** [comment]
DO NOT MERGE I FOUND ANOTHER BUG.

**Comment by 21st-centuryman** [comment]
nvm this is a bug in sz.py as well and tbh its not important

basically if you have a space between your `//` and text it will still count the stuff after the comment.

tbh its not suppose to be a super important thing anyway, its kinda to get a feel for the code.

**Comment by 21st-centuryman** [comment]
you can merge

**Comment by 21st-centuryman** [comment]
Last commit i promise. I added two more lines that basically removes the rest of the line if it detects a comment and then if the vector is empty, ie we have an empty line or the line has a comment, we delete it. The two lines have been extracted and are shown below:
```rs
.take_while(|token| !matches!(token, Token::OP(s) if s == "//"))
.filter(|vec| !vec.is_empty())
```


btw this is functionality that the OG file doesn't have. I thought we should be free to add as many comments as possible.

File: src/tests/sz.rs [hunk 1]
```diff
@@ -6,34 +6,34 @@ use walkdir::WalkDir;
...
+                    tokenize(item.to_string())
+                        .unwrap()
+                        .into_iter()
+                        .filter(|token| {
+                            matches!(
+                                token,
+                                Token::Name(_) | Token::OP(_) | Token::Number(_) | Token::String(_)
+                            )
+                        })
+                        .take_while(|token| !matches!(token, Token::OP(s) if s == "//"))
```
Comment (21st-centuryman) [inline src/tests/sz.rs:28]: This line probably needs some clarification.

basically the `tokenize_py` is based on the python `tokenize` package. 

For some reason the author of this crate decided to make `Token::Comment()` a `#` instead of a `//`. So in order for us to stop taking values after a double forward slash, ie the rest of the line is a comment we need to make it 
```rust
Token::OP("//")
```
and because of issues with Strings we need to add the if statement 
```rust
Token::OP(s) if s == "//"
```

File: src/tests/sz.rs [hunk 2]
```diff
@@ -6,34 +6,34 @@ use walkdir::WalkDir;
...
-                .filter(|token| token.iter().any(&token_whitelist))
-                .collect::<Vec<_>>();
+                .map(|item| {
+                    tokenize(item.to_string())
+                        .unwrap()
+                        .into_iter()
+                        .filter(|token| {
+                            matches!(
+                                token,
+                                Token::Name(_) | Token::OP(_) | Token::Number(_) | Token::String(_)
```
Comment (21st-centuryman) [inline src/tests/sz.rs:25]: Tried to make a whitelist variable but I couldn't be bothered dealing with all the complications that arrises from it, so this is what we are doing.

File: src/tests/sz.rs [hunk 3]
```diff
@@ -6,34 +6,34 @@ use walkdir::WalkDir;
...
+                            )
+                        })
+                        .take_while(|token| !matches!(token, Token::OP(s) if s == "//"))
+                        .collect::<Vec<_>>()
+                })
+                .filter(|vec| !vec.is_empty())
```
Comment (21st-centuryman) [inline src/tests/sz.rs:31]: This is needed if we have any empty lines or if a line has a comment which was removed.

**Comment by 21st-centuryman** [comment]
Had a coffee with Jay and went over this code.

We discussed Rustfmt and comments

seems like its not possble for rustfmt to change the style of comments jay so i think we can just merge this.

I also disabled all merges besides squashing

**Comment by 21st-centuryman** [comment]
Added .DS_Store to the gitignore

closes #59

**Review by Jakunot — APPROVED** [review]
